# Generated by Django 4.1.7 on 2023-09-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_alter_product_pic1_alter_product_pic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='pic5',
            field=models.ImageField(blank=True, default=True, upload_to='uploads'),
        ),
    ]
