# Generated by Django 4.1.7 on 2023-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_buyer_pic5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pic5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
    ]
