# Generated by Django 4.1.7 on 2023-10-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_checkout_checkoutproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='shipping',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
