# Generated by Django 4.1.7 on 2023-10-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_checkoutproduct_qty_checkoutproduct_tatal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutproduct',
            old_name='tatal',
            new_name='total',
        ),
    ]
